/* Auto-generated by gen_note_table.py from code/keyboards_layout/rheinische_tonlage_142_tones/. Do not edit. */

#ifndef KEYBOARD_LAYOUT_H_
#define KEYBOARD_LAYOUT_H_

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MIDI note numbers by name: NOTE(<letter>, <octave>), C4 = 60 (middle C).
 * Append 's' to the letter for sharp, e.g. NOTE(As, 3) = 58.
 * NOTE_NONE marks a key id with no assigned note. */
#define NOTE_NONE 0
#define NOTE_C  0
#define NOTE_Cs 1
#define NOTE_D  2
#define NOTE_Ds 3
#define NOTE_E  4
#define NOTE_F  5
#define NOTE_Fs 6
#define NOTE_G  7
#define NOTE_Gs 8
#define NOTE_A  9
#define NOTE_As 10
#define NOTE_B  11
#define NOTE(name, octave) (((octave) + 1) * 12 + NOTE_##name)

typedef enum { BELLOWS_PULL = 0, BELLOWS_PUSH = 1, BELLOWS_NEUTRAL = 2 } bellows_t;

#define NUM_KEYS 40

extern const uint8_t note_table[3][2][NUM_KEYS];

/* Returns the layout/side name for wing_id, or NULL if wing_id is unknown. */
static inline const char *wing_name(uint8_t wing_id)
{
  switch (wing_id)
  {
    case 1: return "rheinische_tonlage_142_tones_right";
    case 2: return "rheinische_tonlage_142_tones_left";
    default: return NULL;
  }
}

#ifdef __cplusplus
}
#endif

#endif /* KEYBOARD_LAYOUT_H_ */
