remote_theme: "mmistakes/minimal-mistakes@4.27.3"
repository: bandolibre/bandolibre.github.io
rss: rss

title: "L'Atelier"
title_separator: "-"
subtitle: "du Bandonéon Libre"

titles_from_headings:
  strip_title: true
  collections: true

# Site Author
author:
  name             : "Pierre Labatut"
  avatar           : "/assets/images/portrait.webp"
  bio              : "Je code, je joue, je fabrique… <br>parfois tout en même temps."
  location         : "Fontainebleau, FR"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/piwicode"

footer:
  since: "2025"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/piwicode/bandoneo"
    - label: "Mail"
      icon: "fa-solid fa-square-envelope"
      url: "mailto:bandolibre@googlegroups.com"

comments:
  provider: "giscus"
  giscus:
    repo_id: "R_kgDOP5wWLQ"
    category_name: "General"
    category_id: "DIC_kwDOP5wWLc4CwEw7"
    discussion_term: "og:title"
    reactions_enabled: "1"
    theme: light

paypal_link: "https://www.paypal.com/donate/?business=H8ARR8VWJVQZY&no_recurring=0&item_name=acheter+les+composants%2C+fabriquer+les+prototypes+et+continuer+%C3%A0+faire+grandir+le+projet+Bandon%C3%A9o&currency_code=EUR"
google_site_verification: "7jHNeDulfr7YpmrfV3jkmD2w77aXWxKH7enfrSb5VH8"

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-sitemap
  - jemoji
