remote_theme: "mmistakes/minimal-mistakes@4.27.3"
repository: bandolibre/bandolibre.github.io
rss: rss

title: "L'Atelier"
title_separator: "-"
subtitle: "du Bandonéon Libre"

titles_from_headings:
  strip_title: true
  collections: true

footer:
  since: "2025"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/piwicode/bandoneo"
    - label: "Mail"
      icon: "fa-solid fa-square-envelope"
      url: "mailto:bandolibre@googlegroups.com"

comments:
  provider: "giscus"
  giscus:
    repo_id: "R_kgDOP5wWLQ"
    category_name: "General"
    category_id: "DIC_kwDOP5wWLc4CwEw7"
    discussion_term: "og:title"
    reactions_enabled: "1"
    theme: light

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-sitemap
  - jemoji
